### ISSUE TITLE
Табы в пробелы

### ISSUE THREAD

**Issue by NABIRIY** [tapochqa/mail-to-self-clj#1]
чтобы не было уродства
![image](https://user-images.githubusercontent.com/101838630/189042525-affcfcf0-6408-4c33-b74b-8f417243caaf.png)

**Comment by tapochqa** [comment]
самое быстрое закрытие на диком западе

https://github.com/tapochqa/mail-to-self-clj/commit/27e400eab87ce05a0a38c79c7a55605262696680
